version: "3"
services:
  rundeck:
    image: rundeck/rundeck:4.6.0
    ports:
      - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: http://localhost:4440
  gitbucket:
    image: gitbucket/gitbucket
    ports:
      - 8080:8080